env: local
log:
  level: debug
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  sslmode: disable
  timezone: Asia/Jakarta
  max_idle_conn: 10
  max_open_conn: 100
  conn_max_lifetime: 10m